#!/usr/bin/env bash
set -eu

PROJECT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

"$PROJECT_DIR/VERIFICAR_ESTABILIZACION_1_BACKEND.sh"
"$PROJECT_DIR/VERIFICAR_ESTABILIZACION_2_TAREAS.sh"
"$PROJECT_DIR/VERIFICAR_ESTABILIZACION_3_USUARIOS.sh"
"$PROJECT_DIR/VERIFICAR_ESTABILIZACION_4_REPORTES.sh"

echo "RESULTADO GENERAL: CHECKTAP V0.6 APROBADO"
