#!/bin/sh
set -eu
PROJECT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
"$PROJECT_DIR/VERIFICAR_OFFLINE_2.sh"
"$PROJECT_DIR/VERIFICAR_OFFLINE_3.sh"
"$PROJECT_DIR/VERIFICAR_OFFLINE_4.sh"
"$PROJECT_DIR/VERIFICAR_OFFLINE_5.sh"
echo "RESULTADO GENERAL: OFFLINE 2, 3, 4 Y 5 APROBADOS"
